using Microsoft.Extensions.Logging;

namespace ZWave.CommandClasses;

/// <summary>
/// Represents a parsed Security 0 Encapsulation frame.
/// </summary>
public readonly record struct Security0Encapsulation(
    /// <summary>
    /// The de-encapsulated (decrypted) command class frame.
    /// </summary>
    CommandClassFrame EncapsulatedFrame,

    /// <summary>
    /// The frame control byte (sequence counter / sequenced / second-frame flags).
    /// </summary>
    byte FrameControl,

    /// <summary>
    /// Whether the frame is a Security Message Encapsulation Nonce Get (0xC1), meaning the sender
    /// is requesting a fresh nonce from this node (reply with a Nonce Report).
    /// </summary>
    bool RequestedNonce);

public sealed partial class Security0CommandClass
{
    /// <summary>
    /// Creates a Security 0 Encapsulation frame wrapping the specified command for delivery to
    /// <paramref name="destNodeId"/>.
    /// </summary>
    /// <remarks>
    /// Consumes a nonce previously received from the destination (via a Nonce Report) and generates
    /// this node's own nonce. Throws <see cref="ZWaveException"/> with
    /// <c>CommandNotReady</c> if no usable nonce is available. When <paramref name="requestNonce"/>
    /// is set, the frame is a Security Message Encapsulation Nonce Get (0xC1), asking the
    /// destination to send a fresh nonce in reply.
    /// </remarks>
    public CommandClassFrame CreateEncapsulation(CommandClassFrame innerFrame, ushort destNodeId, bool requestNonce = false)
        => CommandEncapsulationCommand.Create(_manager, Endpoint.NodeId, destNodeId, innerFrame, 0x00, requestNonce).Frame;

    /// <summary>
    /// Parses a Security 0 Encapsulation frame received from <paramref name="sourceNodeId"/>.
    /// </summary>
    /// <returns>The de-encapsulated frame, or <c>null</c> if the frame is malformed, the referenced
    /// nonce is unknown/expired, or the MAC does not match.</returns>
    public Security0Encapsulation? ParseEncapsulation(CommandClassFrame frame, ushort sourceNodeId)
        => CommandEncapsulationCommand.Parse(_manager, sourceNodeId, Endpoint.NodeId, frame, Logger);

    /// <summary>
    /// Security 0 Command Encapsulation command (spec §3.5.2).
    /// </summary>
    /// <remarks>
    /// The command ID is 0x81 (Security Message Encapsulation) or 0xC1 (Security Message
    /// Encapsulation Nonce Get). The frame is addressed to the Security CC (0x98); the command ID
    /// is a separate field and is NOT 0x98.
    /// Wire format (command parameters):
    ///   bytes 0..7:   Sender nonce (8 bytes, generated by this node)
    ///   bytes 8..N-9: Ciphertext = AES-128-OFB([frame control][inner command])
    ///   byte  N-9:    Receiver nonce ID (1 byte, first byte of the destination's nonce)
    ///   bytes N-8..N: MAC (8 bytes)
    /// The IV for OFB is [sender nonce][receiver nonce] (16 bytes). Per SDS10865-11 §5.4.1, the MAC
    /// is the first 8 bytes of the final block of AES-128-CBC(authData, auth key, zero IV), where
    ///   authData = [sender nonce][receiver nonce][security header][src node][dst node][ciphertext length][ciphertext].
    /// The security header is the actual outer command ID (0x81 or 0xC1), not the CC ID (0x98); both
    /// sender and receiver must MAC with the byte that appears in the frame.
    /// </remarks>
    internal readonly struct CommandEncapsulationCommand : ICommand
    {
        private const int MinParamsLength = 18;
        private const int NonceLength = 8;
        private const int MacLength = 8;

        public CommandEncapsulationCommand(CommandClassFrame frame)
        {
            Frame = frame;
        }

        public static CommandClassId CommandClassId => CommandClassId.Security0;

        public static byte CommandId => (byte)Security0Command.CommandEncapsulation;

        public CommandClassFrame Frame { get; }

        public static CommandEncapsulationCommand Create(
            S0SecurityManager manager,
            ushort srcNodeId,
            ushort dstNodeId,
            CommandClassFrame innerFrame,
            byte frameControl,
            bool requestNonce = false)
        {
            if (srcNodeId > 255 || dstNodeId > 255)
            {
                ZWaveException.Throw(ZWaveErrorCode.CommandInvalidArgument, "Security 0 only supports 8-bit node IDs");
            }

            if (!manager.HasNetworkKey)
            {
                ZWaveException.Throw(ZWaveErrorCode.CommandNotReady, "No S0 network key has been set for this node");
            }

            ReadOnlySpan<byte> receiverNonce = manager.GetUsableNonce(dstNodeId);
            if (receiverNonce.IsEmpty)
            {
                ZWaveException.Throw(ZWaveErrorCode.CommandNotReady, $"No usable nonce is available for node {dstNodeId}");
            }

            // The sender nonce is used only for this frame's IV and MAC and is carried in the
            // frame itself, so it is generated fresh rather than tracked in the manager's pool.
            byte[] senderNonce = manager.GenerateSenderNonce();

            byte[] plaintext = new byte[1 + innerFrame.Data.Length];
            plaintext[0] = frameControl;
            innerFrame.Data.Span.CopyTo(plaintext.AsSpan(1));

            byte[] encryptionKey = manager.GetEncryptionKey();
            byte[] iv = BuildIv(senderNonce, receiverNonce);
            byte[] ciphertext = S0Crypto.EncryptOfb(plaintext, encryptionKey, iv);
            if (ciphertext.Length > 255)
            {
                ZWaveException.Throw(ZWaveErrorCode.CommandInvalidArgument, "The S0 ciphertext exceeds the 1-byte length limit");
            }

            byte securityHeader = requestNonce
                ? (byte)Security0Command.CommandEncapsulationNonceGet
                : (byte)Security0Command.CommandEncapsulation;

            byte[] authData = BuildAuthData(senderNonce, receiverNonce, securityHeader, srcNodeId, dstNodeId, ciphertext);
            byte[] authKey = manager.GetAuthKey();
            ReadOnlySpan<byte> mac = S0Crypto.ComputeMac(authData, authKey);

            byte[] parameters = new byte[NonceLength + ciphertext.Length + 1 + MacLength];
            int offset = 0;
            senderNonce.CopyTo(parameters.AsSpan(offset));
            offset += NonceLength;
            ciphertext.CopyTo(parameters.AsSpan(offset));
            offset += ciphertext.Length;
            parameters[offset] = receiverNonce[0];
            offset += 1;
            mac.CopyTo(parameters.AsSpan(offset));

            CommandClassFrame frame = CommandClassFrame.Create(CommandClassId, securityHeader, parameters);
            return new CommandEncapsulationCommand(frame);
        }

        public static Security0Encapsulation? Parse(
            S0SecurityManager manager,
            ushort srcNodeId,
            ushort dstNodeId,
            CommandClassFrame frame,
            ILogger logger)
        {
            if (srcNodeId > 255 || dstNodeId > 255)
            {
                logger.LogWarning("Security 0 Encapsulation frame has an unsupported node ID (S0 is 8-bit only)");
                return null;
            }

            if (!manager.HasNetworkKey)
            {
                logger.LogWarning("Security 0 Encapsulation frame received but no network key is set for this node");
                return null;
            }

            byte securityHeader = frame.CommandId;
            if (securityHeader != (byte)Security0Command.CommandEncapsulation
                && securityHeader != (byte)Security0Command.CommandEncapsulationNonceGet)
            {
                logger.LogWarning("Security 0 Encapsulation frame has an unsupported command ID (0x{CommandId:X2})", securityHeader);
                return null;
            }

            ReadOnlySpan<byte> parameters = frame.CommandParameters.Span;
            if (parameters.Length < MinParamsLength)
            {
                logger.LogWarning("Security 0 Encapsulation frame is too short ({Length} bytes)", parameters.Length);
                return null;
            }

            ReadOnlySpan<byte> senderNonce = parameters[..NonceLength];
            ReadOnlySpan<byte> ciphertext = parameters[NonceLength..^9];
            byte nonceId = parameters[^9];
            ReadOnlySpan<byte> mac = parameters[^MacLength..];

            // The nonce must have been issued to the frame's source node; a mismatch (as well as an
            // unknown or expired nonce) is rejected. The lookup and the removal are one atomic
            // operation, and the nonce is consumed before the MAC is validated (spec §3.5.2).
            byte[]? ownNonce = manager.ConsumeOwnNonce(nonceId, srcNodeId);
            if (ownNonce is null)
            {
                logger.LogWarning("Security 0 Encapsulation frame from node {SrcNodeId} references an unknown, expired, or foreign nonce (0x{NonceId:X2})", srcNodeId, nonceId);
                return null;
            }

            byte[] authData = BuildAuthData(senderNonce, ownNonce, securityHeader, srcNodeId, dstNodeId, ciphertext);
            ReadOnlySpan<byte> expectedMac = S0Crypto.ComputeMac(authData, manager.GetAuthKey());
            if (!mac.SequenceEqual(expectedMac))
            {
                logger.LogWarning("Security 0 Encapsulation frame MAC mismatch");
                return null;
            }

            byte[] iv = BuildIv(senderNonce, ownNonce);
            byte[] plaintext = S0Crypto.DecryptOfb(ciphertext, manager.GetEncryptionKey(), iv);
            if (plaintext.Length < 3)
            {
                logger.LogWarning("Security 0 Encapsulation frame decrypted to too short a payload ({Length} bytes)", plaintext.Length);
                return null;
            }

            byte frameControl = plaintext[0];
            CommandClassFrame encapsulatedFrame = new(plaintext[1..]);
            bool requestedNonce = securityHeader == (byte)Security0Command.CommandEncapsulationNonceGet;
            return new Security0Encapsulation(encapsulatedFrame, frameControl, requestedNonce);
        }

        private static byte[] BuildIv(ReadOnlySpan<byte> senderNonce, ReadOnlySpan<byte> receiverNonce)
        {
            byte[] iv = new byte[NonceLength * 2];
            senderNonce.CopyTo(iv);
            receiverNonce.CopyTo(iv.AsSpan(NonceLength));
            return iv;
        }

        private static byte[] BuildAuthData(
            ReadOnlySpan<byte> senderNonce,
            ReadOnlySpan<byte> receiverNonce,
            byte securityHeader,
            ushort srcNodeId,
            ushort dstNodeId,
            ReadOnlySpan<byte> ciphertext)
        {
            byte[] authData = new byte[NonceLength * 2 + 4 + ciphertext.Length];
            int offset = 0;
            senderNonce.CopyTo(authData.AsSpan(offset));
            offset += NonceLength;
            receiverNonce.CopyTo(authData.AsSpan(offset));
            offset += NonceLength;
            authData[offset] = securityHeader;
            offset += 1;
            authData[offset] = (byte)srcNodeId;
            offset += 1;
            authData[offset] = (byte)dstNodeId;
            offset += 1;
            authData[offset] = (byte)ciphertext.Length;
            offset += 1;
            ciphertext.CopyTo(authData.AsSpan(offset));
            return authData;
        }
    }
}
