using Microsoft.Extensions.Logging.Abstractions;

namespace ZWave.CommandClasses.Tests;

public partial class Security0CommandClassTests
{
    [TestMethod]
    public void Encapsulation_TwoPartyARoundTripsB()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        // The receiver generates its nonce; the sender stores it as if received via a Nonce Report.
        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, command.Frame, NullLogger.Instance);

        Assert.IsNotNull(result);
        Assert.AreEqual((byte)0x00, result.Value.FrameControl);
        Assert.AreEqual(Hex(inner.Data.Span.ToArray()), Hex(result.Value.EncapsulatedFrame.Data.Span.ToArray()));
    }

    [TestMethod]
    public void Encapsulation_CiphertextDiffersFromPlaintext()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01, 0x02, 0x03]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        byte[] plaintext = new byte[1 + inner.Data.Length];
        plaintext[0] = 0x00;
        inner.Data.Span.CopyTo(plaintext.AsSpan(1));
        byte[] parameters = command.Frame.CommandParameters.Span.ToArray();
        byte[] ciphertext = parameters.AsSpan()[8..(8 + plaintext.Length)].ToArray();

        Assert.IsFalse(ciphertext.SequenceEqual(plaintext));
    }

    [TestMethod]
    public void Encapsulation_TamperedCiphertext_MacMismatch_ReturnsNull()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        byte[] data = command.Frame.Data.Span.ToArray();
        data[10] ^= 0xFF; // first ciphertext byte (offset 2 for CC+cmd, 8 for sender nonce)
        CommandClassFrame tampered = new(data);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, tampered, NullLogger.Instance);

        Assert.IsNull(result);
    }

    [TestMethod]
    public void Encapsulation_WrongNetworkKey_ReturnsNull()
    {
        S0SecurityManager sender = new(ownNodeId: 1);
        S0SecurityManager receiver = new(ownNodeId: 2);
        sender.SetNetworkKey(NetworkKey);
        receiver.SetNetworkKey(Convert.FromHexString("00112233445566778899aabbccddeeff"));

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, command.Frame, NullLogger.Instance);

        Assert.IsNull(result);
    }

    [TestMethod]
    public void Encapsulation_UnknownNonce_ReturnsNull()
    {
        S0SecurityManager sender = new(ownNodeId: 1);
        S0SecurityManager receiver = new(ownNodeId: 2);
        S0SecurityManager nonceProvider = new(ownNodeId: 2);
        sender.SetNetworkKey(NetworkKey);
        receiver.SetNetworkKey(NetworkKey);
        nonceProvider.SetNetworkKey(NetworkKey);

        // The nonce is generated by a different instance, so the receiver does not know it.
        byte[] receiverNonce = nonceProvider.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, command.Frame, NullLogger.Instance);

        Assert.IsNull(result);
    }

    [TestMethod]
    public void Encapsulation_TooShortFrame_ReturnsNull()
    {
        S0SecurityManager receiver = new(ownNodeId: 2);
        receiver.SetNetworkKey(NetworkKey);
        CommandClassFrame frame = new(new byte[] { 0x98, 0x81, 0x00, 0x00, 0x00 });

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, frame, NullLogger.Instance);

        Assert.IsNull(result);
    }

    [TestMethod]
    public void Encapsulation_Create_NoUsableNonce_Throws()
    {
        S0SecurityManager sender = new(ownNodeId: 1);
        sender.SetNetworkKey(NetworkKey);
        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);

        Assert.Throws<ZWaveException>(() =>
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00));
    }

    [TestMethod]
    public void Encapsulation_Create_NoNetworkKey_Throws()
    {
        S0SecurityManager sender = new(ownNodeId: 1);
        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);

        Assert.Throws<ZWaveException>(() =>
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00));
    }

    [TestMethod]
    public void Encapsulation_Create_UnsupportedNodeId_Throws()
    {
        S0SecurityManager sender = new(ownNodeId: 1);
        sender.SetNetworkKey(NetworkKey);
        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);

        Assert.Throws<ZWaveException>(() =>
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 300, dstNodeId: 2, inner, 0x00));
    }

    [TestMethod]
    public void Encapsulation_NonceGet_RoundTripsWithRequestedNonce()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00, requestNonce: true);

        Assert.AreEqual((byte)Security0Command.CommandEncapsulationNonceGet, command.Frame.CommandId);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, command.Frame, NullLogger.Instance);

        Assert.IsNotNull(result);
        Assert.IsTrue(result.Value.RequestedNonce);
        Assert.AreEqual(Hex(inner.Data.Span.ToArray()), Hex(result.Value.EncapsulatedFrame.Data.Span.ToArray()));
    }

    [TestMethod]
    public void Encapsulation_Default_RoundTripsWithoutRequestedNonce()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        Assert.AreEqual((byte)Security0Command.CommandEncapsulation, command.Frame.CommandId);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, command.Frame, NullLogger.Instance);

        Assert.IsNotNull(result);
        Assert.IsFalse(result.Value.RequestedNonce);
    }

    [TestMethod]
    public void Encapsulation_UnsupportedCommandId_ReturnsNull()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        // Overwrite the command ID (byte 1) with a value that is neither 0x81 nor 0xC1.
        byte[] data = command.Frame.Data.Span.ToArray();
        data[1] = 0x98;
        CommandClassFrame badCommandId = new(data);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 1, dstNodeId: 2, badCommandId, NullLogger.Instance);

        Assert.IsNull(result);
    }

    [TestMethod]
    public void Encapsulation_SenderNonce_NotTrackedInOwnPool()
    {
        (S0SecurityManager sender, S0SecurityManager receiver) = CreateManagers();

        byte[] receiverNonce = receiver.GenerateNonce(receiver: 1);
        sender.StoreReceivedNonce(issuer: 2, receiverNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(sender, srcNodeId: 1, dstNodeId: 2, inner, 0x00);

        // The sender nonce is the first 8 bytes of the command parameters. It must not be
        // retrievable from the sender's own pool: it was generated for this frame, not issued
        // to a peer, so Parse must never accept an inbound command that references it.
        byte[] senderNonce = command.Frame.CommandParameters.Span[..8].ToArray();
        ReadOnlySpan<byte> ownNonce = sender.GetOwnNonce(senderNonce[0], sourceNodeId: 2);

        Assert.IsTrue(ownNonce.IsEmpty);
    }

    [TestMethod]
    public void Encapsulation_NonceIssuedToOtherPeer_RejectsFrameFromDifferentNode()
    {
        // Node 1 issues a nonce to peer 2. A different node (3) that has learned the nonce value
        // (e.g. by eavesdropping the Nonce Report) must not be able to consume node 1's nonce
        // slot, even though it can compute a valid MAC (all S0 nodes share the network key).
        S0SecurityManager receiver = new(ownNodeId: 1);
        receiver.SetNetworkKey(NetworkKey);
        byte[] issuedNonce = receiver.GenerateNonce(receiver: 2);

        S0SecurityManager attacker = new(ownNodeId: 3);
        attacker.SetNetworkKey(NetworkKey);
        attacker.StoreReceivedNonce(issuer: 1, issuedNonce);

        CommandClassFrame inner = CommandClassFrame.Create(CommandClassId.BinarySwitch, 0x01, [0x01]);
        Security0CommandClass.CommandEncapsulationCommand command =
            Security0CommandClass.CommandEncapsulationCommand.Create(attacker, srcNodeId: 3, dstNodeId: 1, inner, 0x00);

        Security0Encapsulation? result =
            Security0CommandClass.CommandEncapsulationCommand.Parse(receiver, srcNodeId: 3, dstNodeId: 1, command.Frame, NullLogger.Instance);

        Assert.IsNull(result);
    }

    [TestMethod]
    public void ConsumeOwnNonce_ConcurrentCalls_OnlyOneConsumes()
    {
        // A nonce is single-use, so of many concurrent attempts to consume the same nonce ID,
        // exactly one must succeed. This is the invariant the atomic lookup-and-remove in
        // ConsumeOwnNonce enforces (a split check-then-delete would let two callers through).
        S0SecurityManager manager = new(ownNodeId: 1);
        byte[] nonce = manager.GenerateNonce(receiver: 2);
        byte nonceId = nonce[0];

        const int Callers = 32;
        Task<byte[]?>[] tasks = new Task<byte[]?>[Callers];
        for (int i = 0; i < Callers; i++)
        {
            tasks[i] = Task.Run(() => manager.ConsumeOwnNonce(nonceId, sourceNodeId: 2));
        }

        Task.WaitAll(tasks);

        int consumed = 0;
        foreach (Task<byte[]?> task in tasks)
        {
            if (task.Result is not null)
            {
                consumed++;
            }
        }

        Assert.AreEqual(1, consumed);
    }
}
