namespace ZWave.Serial.Commands;

/// <summary>
/// Nonce management sub-commands.
/// </summary>
public enum NonceSubCommand : byte
{
    /// <summary>
    /// Set the nonce generation mode.
    /// </summary>
    SetMode = 0x01,

    /// <summary>
    /// Nonce update notification from the Z-Wave module.
    /// </summary>
    NonceUpdate = 0x02,
}

/// <summary>
/// Enable Nonce Generation on the Z-Wave Module.
/// </summary>
public readonly struct NonceGenerationSetModeRequest : ICommand<NonceGenerationSetModeRequest>
{
    public NonceGenerationSetModeRequest(DataFrame frame)
    {
        Frame = frame;
    }

    public static DataFrameType Type => DataFrameType.REQ;

    public static CommandId CommandId => CommandId.NonceGenerationSetMode;

    public DataFrame Frame { get; }

    /// <summary>
    /// Create a request to set the nonce generation mode.
    /// </summary>
    /// <param name="enable">Whether to enable (true) or disable (false) nonce generation.</param>
    public static NonceGenerationSetModeRequest Create(bool enable)
    {
        ReadOnlySpan<byte> commandParameters =
        [
            (byte)NonceSubCommand.SetMode,
            enable ? (byte)0x01 : (byte)0x00,
        ];
        DataFrame frame = DataFrame.Create(Type, CommandId, commandParameters);
        return new NonceGenerationSetModeRequest(frame);
    }

    public static NonceGenerationSetModeRequest Create(DataFrame frame, CommandParsingContext context) => new NonceGenerationSetModeRequest(frame);
}

/// <summary>
/// Response to a <see cref="NonceGenerationSetModeRequest"/> command.
/// </summary>
public readonly struct NonceGenerationSetModeResponse : ICommand<NonceGenerationSetModeResponse>
{
    public NonceGenerationSetModeResponse(DataFrame frame)
    {
        Frame = frame;
    }

    public static DataFrameType Type => DataFrameType.RES;

    public static CommandId CommandId => CommandId.NonceGenerationSetMode;

    public DataFrame Frame { get; }

    /// <summary>
    /// The sub-command this response corresponds to.
    /// </summary>
    public NonceSubCommand SubCommand => (NonceSubCommand)Frame.CommandParameters.Span[0];

    /// <summary>
    /// The command status (0x01 = success, 0x00 = failure).
    /// </summary>
    public byte CommandStatus => Frame.CommandParameters.Span[1];

    public static NonceGenerationSetModeResponse Create(DataFrame frame, CommandParsingContext context) => new NonceGenerationSetModeResponse(frame);
}

/// <summary>
/// The type of payload in a nonce update notification.
/// </summary>
public enum NoncePayloadType : byte
{
    /// <summary>
    /// The payload contains a 16-byte nonce generated by the Z-Wave module.
    /// This also indicates that the newly generated nonce has been sent to
    /// the requesting node via S2 Nonce Report Command.
    /// </summary>
    Nonce = 0x01,
}

/// <summary>
/// Unsolicited nonce update notification from the Z-Wave module.
/// </summary>
public readonly struct NonceUpdate : ICommand<NonceUpdate>
{
    private readonly NodeIdType _nodeIdType;

    public NonceUpdate(DataFrame frame, NodeIdType nodeIdType)
    {
        Frame = frame;
        _nodeIdType = nodeIdType;
    }

    public static DataFrameType Type => DataFrameType.REQ;

    public static CommandId CommandId => CommandId.NonceGenerationSetMode;

    public DataFrame Frame { get; }

    /// <summary>
    /// The sub-command (always <see cref="NonceSubCommand.NonceUpdate"/>).
    /// </summary>
    public NonceSubCommand SubCommand => (NonceSubCommand)Frame.CommandParameters.Span[0];

    /// <summary>
    /// The source node ID.
    /// </summary>
    public ushort SourceNodeId => _nodeIdType.ReadNodeId(Frame.CommandParameters.Span, 1);

    /// <summary>
    /// The payload type.
    /// </summary>
    public NoncePayloadType PayloadType => (NoncePayloadType)Frame.CommandParameters.Span[1 + _nodeIdType.NodeIdSize()];

    /// <summary>
    /// The nonce update payload.
    /// </summary>
    public ReadOnlyMemory<byte> Payload => Frame.CommandParameters.Slice(3 + _nodeIdType.NodeIdSize(), Frame.CommandParameters.Span[2 + _nodeIdType.NodeIdSize()]);

    public static NonceUpdate Create(DataFrame frame, CommandParsingContext context) => new NonceUpdate(frame, context.NodeIdType);
}
